# Generated by Django 5.2 on 2026-07-05 23:47

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="название навыка"
                    ),
                ),
            ],
            options={
                "verbose_name": "навык",
                "verbose_name_plural": "навыки",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="фамилия")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        help_text="необязательно",
                        max_length=50,
                        null=True,
                        verbose_name="отчество",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Мужской"), ("F", "Женский"), ("O", "Другой")],
                        max_length=1,
                        null=True,
                        verbose_name="пол",
                    ),
                ),
                (
                    "description",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True,
                        help_text="WYSIWYG-редактор (Django ckeditor 5)",
                        verbose_name="описание",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "профиль сотрудника",
                "verbose_name_plural": "профили сотрудников",
            },
        ),
        migrations.CreateModel(
            name="EmployeeSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="от 1 до 10",
                        verbose_name="уровень освоения",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to="employees.employeeprofile",
                        verbose_name="сотрудник",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_skills",
                        to="employees.skill",
                        verbose_name="навык",
                    ),
                ),
            ],
            options={
                "verbose_name": "уровень навыка сотрудника",
                "verbose_name_plural": "уровни навыков сотрудников",
            },
        ),
        migrations.AddField(
            model_name="employeeprofile",
            name="skills",
            field=models.ManyToManyField(
                related_name="employees",
                through="employees.EmployeeSkill",
                to="employees.skill",
                verbose_name="навыки",
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeskill",
            constraint=models.CheckConstraint(
                condition=models.Q(("level__gte", 1), ("level__lte", 10)),
                name="level_between_1_and_10",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeeskill",
            unique_together={("employee", "skill")},
        ),
    ]
