# Generated by Django 5.2 on 2026-08-05 21:53

import employees.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employeeprofile_hire_date_alter_employeeprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeprofile",
            name="hire_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[employees.validators.validate_hire_date],
                verbose_name="дата приёма на работу",
            ),
        ),
    ]
