# Generated by Django 5.2 on 2026-07-05 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        help_text="например, A12, 305, B-02",
                        max_length=20,
                        unique=True,
                        verbose_name="номер стола",
                    ),
                ),
                (
                    "extra_info",
                    models.TextField(
                        blank=True,
                        help_text="любые примечания по рабочему месту",
                        verbose_name="дополнительная информация",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="дата обновления"),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="desk",
                        to="employees.employeeprofile",
                        verbose_name="закреплённый сотрудник",
                    ),
                ),
            ],
            options={
                "verbose_name": "рабочее место",
                "verbose_name_plural": "рабочие места",
                "ordering": ["number"],
            },
        ),
    ]
