# Generated by Django 5.2 on 2026-08-06 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desks", "0001_initial"),
        ("employees", "0005_alter_employeeprofile_hire_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="desk",
            name="responsible",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responsible_for_desks",
                to="employees.employeeprofile",
            ),
        ),
    ]
