# Generated by Django 5.2 on 2026-08-07 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("desks", "0002_desk_responsible"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="desk",
            name="responsible",
        ),
    ]
